# Generated by Django 4.2.13 on 2024-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("STU_NAME", models.CharField(max_length=500)),
                ("STU_EMAIL", models.CharField(max_length=500)),
                ("STU_DEPT", models.CharField(max_length=500)),
            ],
        ),
    ]
